### ISSUE TITLE
Is Facebook truly a requirement?

### ISSUE THREAD

**Issue by antonywu** [matthieu-beteille/gipher#3]
I get why Tinder wants people to use Facebook to sign in, but why does Gipher need Facebook? Just to be fair, can we have Google login? I stopped using Facebook for over 4 years now, but I maintain active Google account.

**Comment by azinman** [comment]
Or no login just to see what it is??!

**Comment by mLuby** [comment]
+1 was going to share this repo but can't actually see the app without FB.

**Comment by mt-bt** [comment]
Hey,

Thanks for the feedbacks, I just added a quick signup/login so that you can try it out :+1:
